name: CI

on: [pull_request, push]

jobs:
  install:
    name: Instalando packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules

      - name: Instalando dependencias
        run: npm install

  testing:
    - name: Testando
      run: npm test

  coverage:
    name: Análise de Cobertura
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run JaCoCo for Code Coverage
        run: mvn jacoco:prepare-agent test jacoco:report

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco
